tinymce/tinymce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymceeditor/', include('tinymceeditor.urls')),
]

tinymce/tinymceeditor/urls.py
from django.contrib import admin
from django.urls import include, path

from tinymceeditor import views

app_name = 'tinymceeditor'
urlpatterns = [
    path('', views.index, name='index'),
]

tinymce/tinymceeditor/models.py
from django.db import models

# Create your models here.

class Note(models.Model):
    note = models.TextField('Note', max_length=1000)
    created_at = models.DateTimeField('date created', auto_now_add=True)

    def __str__(self):
        return self.note[:50]

tinymce/tinymceeditor/views.py
from django.shortcuts import render

# Create your views here.
from .models import Note

def index(request):
    all_notes = Note.objects.all()
    context = { 'result': '',
                'notes': all_notes}

    if request.method == 'POST':
        result = request.POST.get('mytextarea')
        print(result)
        context['result'] = result
        note = Note(note=result)
        note.save()
    return render(request, 'tinymceeditor/index.html', context)

tinymce/tinymceeditor/templates/tinymceeditor/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <script src="https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>

    <script>
        tinymce.init({
            selector: '#mytextarea'
        });
    </script>

</head>

<body>
<h1>TinyMCE Quick Start Guide</h1>
<form method="post" action="{% url 'tinymceeditor:index' %}">
    {% csrf_token %}
    <textarea id="mytextarea" name="mytextarea">Hello, World!</textarea>
    <button>Submit</button>
</form>
<div>
    <h2>Result</h2>
    <p>{{ result }}</p>
</div>

<h2> All notes</h2>
{% for note in notes %}
    <div>
        <p>
            {{ note.created_at }}
        </p>
        <p>
            {% autoescape off %}
            {{ note.note }}
            {% endautoescape %}
        </p>
    </div>
{% endfor %}
</body>
</html>